import "./globals.css";
import type { Metadata } from "next";
import { Roboto_Condensed, Roboto_Slab } from "next/font/google";
import { WrapperQueryClientProvider } from "../tanstack/queryProvider";
import { ContextBgProvider } from "../context/bgContext";

const robotoSlab = Roboto_Slab({
  variable: "--font-roboto_slab",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  display: 'swap'
});

const robotoCondense = Roboto_Condensed({
  variable: "--font-roboto_cond",
  subsets: ["latin"],
  weight: ["500"],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${robotoCondense.variable} ${robotoSlab.variable} h-full antialiased`}
    >
      <WrapperQueryClientProvider>
        <ContextBgProvider>
          <body className="min-h-full flex flex-col">
            {children}
          </body>
        </ContextBgProvider>
      </WrapperQueryClientProvider>
    </html>
  );
}
